Repository NREL/flasc, pull requests merged in 2023-03, with the labels that each got.

#72 Feature: Energy ratio polar plots and wind speed distributions
  examples/energy_ratio/energy_ratio_vs_wd_for_multiple_dfs.py
  examples/energy_ratio/energy_ratio_vs_wd_for_single_df.py
  flasc/energy_ratio/energy_ratio.py
  flasc/energy_ratio/energy_ratio_suite.py
  flasc/energy_ratio/energy_ratio_visualization.py
  requirements.txt
  setup.py
Labels: enhancement

#26 Enforce user to specify ti
  flasc/energy_ratio/energy_ratio_wd_bias_estimation.py
  flasc/floris_tools.py
  tests/floris_tools_test.py
Labels: enhancement

#76 Add conversion from char to rgb
  flasc/energy_ratio/energy_ratio_visualization.py
Labels: bug

#74 Feature: Addressing irregular turbine behavior of neighboring turbines (e.g., curtailment)
  flasc/dataframe_operations/dataframe_filtering.py
  flasc/dataframe_operations/dataframe_manipulations.py
  flasc/energy_ratio/energy_ratio_suite.py
  flasc/energy_ratio/energy_ratio_wd_bias_estimation.py
  flasc/floris_tools.py
  tests/df_filtering_test.py
  tests/floris_tools_test.py
Labels: bug, enhancement
