Repository NREL/flasc, pull requests merged in 2024-04, with the labels that each got.

#178 [BUGFIX] Track FLORIS v4 changes
  examples_artificial_data/00_setup_floris_model/00_visualize_layout.py
  examples_artificial_data/00_setup_floris_model/01_visualize_flowfield.py
  examples_artificial_data/00_setup_floris_model/02_precalculate_floris_solutions.py
  examples_artificial_data/00_setup_floris_model/03_compute_turbine_dependencies.py
  examples_artificial_data/00_setup_floris_model/04_geometric_dependencies.py
  examples_artificial_data/01_raw_data_processing/00_filter_ws_power_curves.ipynb
  examples_artificial_data/01_raw_data_processing/01_northing_calibration.ipynb
  examples_artificial_data/02_wake_steering_design/00_analyze_single_ws_vs_range.py
  examples_artificial_data/02_wake_steering_design/01_analyze_cosine_exponent_values.py
  examples_artificial_data/02_wake_steering_design/02_analyze_wdstd_choices.py
  examples_artificial_data/02_wake_steering_design/03_analyze_ti_choices.py
  examples_artificial_data/02_wake_steering_design/_local_helper_functions.py
  examples_artificial_data/03_energy_ratio/00_demo_energy_ratio_syntax.ipynb
  examples_artificial_data/03_energy_ratio/01_demo_energy_ratio_options.ipynb
  examples_artificial_data/03_energy_ratio/02_energy_ratio_vs_wd_for_single_df.py
  examples_artificial_data/03_energy_ratio/03_energy_ratio_vs_wd_for_multiple_dfs.py
  examples_artificial_data/03_energy_ratio/04_energy_ratio_in_turbine_array.py
  examples_artificial_data/03_energy_ratio/05_estimate_heterogeneity_from_energy_ratios.py
  examples_artificial_data/03_energy_ratio/06_wake_steering_example.py
  examples_artificial_data/03_energy_ratio/07_wake_steering_total_uplift.py
  examples_artificial_data/04_floris_tuning/00_tune_floris_to_artificial_data.ipynb
  examples_artificial_data/floris_input_artificial/cc.yaml
  examples_artificial_data/floris_input_artificial/emgauss.yaml
  examples_artificial_data/floris_input_artificial/gch.yaml
  examples_artificial_data/floris_input_artificial/jensen.yaml
  examples_artificial_data/floris_input_artificial/turbopark.yaml
  examples_smarteole/00_inspect_floris_model.ipynb
  examples_smarteole/01_precalculate_floris_solutions.ipynb
  examples_smarteole/02_download_and_format_dataset.ipynb
  examples_smarteole/03_filter_ws_power_curves.ipynb
  examples_smarteole/04_northing_calibration.ipynb
  examples_smarteole/05_baseline_energy_ratio_analysis.ipynb
  examples_smarteole/06_wake_steering_energy_ratio_analysis.ipynb
  examples_smarteole/07_emgauss_scada_tuning_optimization_method.ipynb
  examples_smarteole/08_emgauss_tuning_day_night.ipynb
  examples_smarteole/floris_input_smarteole/cc.yaml
  examples_smarteole/floris_input_smarteole/emgauss.yaml
  examples_smarteole/floris_input_smarteole/gch.yaml
  examples_smarteole/floris_input_smarteole/jensen.yaml
  examples_smarteole/floris_input_smarteole/senvion_MM82.yaml
  examples_smarteole/floris_input_smarteole/turbopark.yaml
  flasc/analysis/energy_ratio_heterogeneity_mapper.py
  flasc/data_processing/energy_ratio_wd_bias_estimation.py
  flasc/data_processing/northing_offset.py
  flasc/data_processing/ws_pow_filtering.py
  flasc/model_fitting/floris_sensitivity_analysis.py
  flasc/model_fitting/floris_tuning.py
  flasc/model_fitting/turbulence_estimator.py
  flasc/utilities/floris_tools.py
  flasc/utilities/optimization.py
  flasc/utilities/tuner_utilities.py
  flasc/utilities/utilities_examples.py
  flasc/visualization.py
  tests/df_filtering_test.py
  tests/energy_ratio_test.py
  tests/floris_tools_test.py
Labels: v2.0

#173 Add names to filtering
  flasc/data_processing/ws_pow_filtering.py
Labels: enhancement

#172 Add logging to FLASC
  examples_artificial_data/_legacy/parameter_estimation/estimate_ti_floris_debug.py
  examples_artificial_data/_legacy/sensitivity_analysis/sensitivity_analysis_suite.py
  examples_artificial_data/_legacy/sensitivity_analysis/simple_sobol_example.py
  examples_artificial_data/_legacy/table_analysis/energy_table_for_two_df.py
  examples_artificial_data/_legacy/table_analysis/test_out_table.ipynb
  flasc/analysis/energy_ratio.py
  flasc/analysis/energy_ratio_heterogeneity_mapper.py
  flasc/analysis/total_uplift.py
  flasc/data_processing/dataframe_filtering.py
  flasc/data_processing/dataframe_manipulations.py
  flasc/data_processing/energy_ratio_wd_bias_estimation.py
  flasc/data_processing/find_sensor_faults.py
  flasc/data_processing/northing_offset.py
  flasc/data_processing/time_operations.py
  flasc/data_processing/ws_pow_filtering.py
  flasc/logging_manager.py
  flasc/model_fitting/floris_sensitivity_analysis.py
  flasc/model_fitting/turbulence_estimator.py
  flasc/model_fitting/yaw_pow_fitting.py
  flasc/utilities/floris_tools.py
  flasc/utilities/optimization.py
  flasc/utilities/utilities.py
  flasc/yaw_optimizer_visualization.py
  setup.py
  tests/energy_ratio_test.py
Labels: enhancement, v2.0

#185 Feature/rename ws pw curve filtering
  docs/data_processing.rst
  examples_artificial_data/01_raw_data_processing/00_filter_ws_power_curves.ipynb
  examples_artificial_data/01_raw_data_processing/01_northing_calibration.ipynb
  examples_smarteole/03_filter_ws_power_curves.ipynb
  examples_smarteole/04_northing_calibration.ipynb
  examples_smarteole/06_wake_steering_energy_ratio_analysis.ipynb
  flasc/data_processing/__init__.py
  flasc/data_processing/dataframe_filtering.py
  flasc/data_processing/filtering.py
  tests/df_filtering_test.py
Labels: v2.0

#184 [BUGFIX] reset_operation need in artificial data tuning example
  examples_artificial_data/04_floris_tuning/00_tune_floris_to_artificial_data.ipynb
Labels: bug, v2.0

#187 Minor documentation improvements for v2
  docs/getting_started.md
  docs/getting_started.rst
  docs/overview.md
Labels: v2.0

#189 bug fix in plot_layout
  flasc/analysis/energy_ratio_heterogeneity_mapper.py
Labels: bug, v2.0
