Repository NREL/flasc, pull requests merged in 2024-08, with the labels that each got.

#197 Feature/add docstrings
  .github/workflows/continuous-integration-workflow.yaml
  docs/overview.md
  flasc/analysis/energy_ratio.py
  flasc/analysis/energy_ratio_heterogeneity_mapper.py
  flasc/analysis/energy_ratio_input.py
  flasc/analysis/energy_ratio_output.py
  flasc/analysis/total_uplift.py
  flasc/data_processing/dataframe_manipulations.py
  flasc/data_processing/energy_ratio_wd_bias_estimation.py
  flasc/data_processing/filtering.py
  flasc/data_processing/find_sensor_faults.py
  flasc/data_processing/northing_offset.py
  flasc/data_processing/time_operations.py
  flasc/logging_manager.py
  flasc/model_fitting/floris_sensitivity_analysis.py
  flasc/model_fitting/floris_tuning.py
  flasc/model_fitting/turbulence_estimator.py
  flasc/model_fitting/yaw_pow_fitting.py
  flasc/utilities/circular_statistics.py
  flasc/utilities/energy_ratio_utilities.py
  flasc/utilities/floris_tools.py
  flasc/utilities/lookup_table_tools.py
  flasc/utilities/optimization.py
  flasc/utilities/tuner_utilities.py
  flasc/utilities/utilities.py
  flasc/utilities/utilities_examples.py
  flasc/visualization.py
  flasc/yaw_optimizer_visualization.py
  pyproject.toml
Labels: documentation

#202 Update coloredlogs requirement for FLORIS consistency
  setup.py
Labels: bug

#204 Update docs to describe PyPI installation.
  docs/installation.md
Labels: bug, documentation
